#RabbitMQ Configuration
spring:
  cloud:
    stream:
      source: eventPublisher
      bindings:
        eventPublisher-out-1:
          destination: rezepte.sweng
          binder: cloud_rabbit
        eventConsumer-in-0:
          destination: register.sweng
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rat.rmq2.cloudamqp.com
                port: 5672
                username: ggdnciei
                password: sRTIifxJVr2UxTH5VE1aPiYm0KHMDXMG
                virtual-host: ggdnciei

  #repeat the rabbitmq credentials as follows when actuator health checks are active:
  rabbitmq:
    host: rat.rmq2.cloudamqp.com
    port: 5672
    username: ggdnciei
    password: sRTIifxJVr2UxTH5VE1aPiYm0KHMDXMG
    virtual-host: ggdnciei
