#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: eventConsumer;eventPublisher
    stream:
      bindings:
        eventPublisher-out-0:
          destination: test.sweng
          binder: cloud_rabbit
        eventConsumer-in-0:
          destination: test.sweng
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.team12.svc.cluster.local
                port: 5672
                username: admin
                password: password
                virtual-host: harrytest
  #repeat the rabbitmq credentials as follows when actuator health checks are active:
  rabbitmq:
    host: rabbitmq.team12.svc.cluster.local
    port: 5672
    username: admin
    password: password
    virtual-host: harrytest